# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Mesh' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mesh
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
